model_type: "yolov8"
model_path: "/home/juliocesar/leaf-detection/checkpoints/yolov10/large/train4/best.pt"
data_classes: ["leaf"]
sam2_path: "/home/juliocesar/leaf-detection/checkpoints/sam2/sam2_hiera_tiny.pt"
sam2_cfg: "sam2_hiera_t.yaml"
detection_parameters:
  confidence: 50.0
  overlap: 50.0
  slice_detect: False
  slice_wh: [480,480]
  slice_overlap_ratio: [0.3,0.3]
  slice_iou_threshold: 0.2
  slice_fill: False
